---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 2
    #Statica proxy will not work with localhost so replace this with cloud db url to test.
    url: jdbc:mysql://127.0.0.1/pong_matcher_spring_development
    username: springpong
    password: springpong
  jpa:
    hibernate.ddl-auto: none
    show_sql: false
